def imageName = 'mlabouardy/movies-loader'
def registry = 'https://registry.slowcoder.com'

pipeline {
    agent none
    options {
        skipStagesAfterUnstable()
    }
      stages{
           
        stage('Unit Tests'){
            steps{
                script {
                    def imageTest= docker.build("${imageName}-test", "-f Dockerfile.test .")
                    imageTest.inside{
                        sh "python test_main.py"
                    }
                }
            }
        }
           
        stage('Build') {
            steps {
                script {
                 def image= docker.build("${imageName}")
               }
            }
         }

           
     }
 }
