def imageName = 'mlabouardy/movies-loader'
def registry = 'https://registry.slowcoder.com'

pipeline {
    agent none
    options {
        skipStagesAfterUnstable()
    }
    stages{
        stage('Checkout'){
            steps{
                checkout scm
            }
        }
   
        stage('Test') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                  sh 'python -m py_compile test_main.py'
           
        }
        stage('Build') {
            steps {
                script {
                 def image= docker.build("${imageName}")
                 }
            }
 
        }

    }
}
